### ISSUE TITLE
Communication Between two microservices using ASP.Net Core WebApi

### ISSUE THREAD

**Issue by kmuthugtk** [WolfgangOfner/MicroserviceDemo#9]
I have two Microservices. First Service for Customers and Second service for Invoice Service.

In Invoice MicroService, I will save only CustomerId in Invoice services. Using this CustomerId, I would like to retrieve all the related data for Customer Microservice. But i don't know to communicate async.

Any please get me some ideas and examples

**Comment by WolfgangOfner** [comment]
You shouldn't have an asynchronous communication in this case because you need the information immediately. 

The Invoice service should call a GetCustomerById() method on the Customer service to retrieve the information. If the Customer service is offline, you won't be able to retrieve the information at that time. 

To have a more resilient Invoice service, you could copy the Customer data into the invoice data. The downside of this approach is that you have to update the Customer data regularly and it might be possible that the Invoice service has outdata customer information when you access it. The advantage is that you can always create or display the invoice data because you always have the customer data.

It depends on the business requirements which approach is better, therefore, I can't tell you what approach you should implement.
